### ISSUE TITLE
Cache Policy Errors at runtime

### ISSUE THREAD

**Issue by ADNolan** [contentstack/contentstack-typescript#57]
I am attempting to use the SDK cache feature and running into an error with the following configuration. current package version is 
`@contentstack/delivery-sdk": "4.3.0`

```
{
    policy: 'NETWORK_ELSE_CACHE',
    storeType: 'memoryStorage',
    maxAge: 600000
  }
```

```
TypeError [Error]: defaultAdapter is not a function
        at <anonymous> (node_modules/@contentstack/delivery-sdk/src/lib/cache.ts:17:33)
        at Generator.next (<anonymous>)
        at node_modules/tslib/tslib.js:169:75
        at new Promise (<anonymous>)
        at Object.__awaiter (node_modules/tslib/tslib.js:165:16)
        at handleRequest (node_modules/@contentstack/delivery-sdk/src/lib/cache.ts:12:14)
        at Object.<anonymous> (node_modules/@contentstack/delivery-sdk/src/lib/contentstack.ts:97:30)
        at Generator.next (<anonymous>)
        at node_modules/tslib/tslib.js:169:75
        at new Promise (<anonymous>)
```

When setting to use a different policy, another error arises.
```
{
    policy: 'CACHE_ELSE_NETWORK',
    storeType: 'memoryStorage',
    maxAge: 600000
  }
```

```
 TypeError [Error]: Cannot read properties of undefined (reading 'getItem')
      at Object.getItem (node_modules/@contentstack/delivery-sdk/src/persistance/storages/local-storage.ts:36:25)
      at PersistanceStore.getItem (node_modules/@contentstack/delivery-sdk/src/persistance/persistance-store.ts:64:32)
      at <anonymous> (node_modules/@contentstack/delivery-sdk/src/lib/cache.ts:59:40)
      at Generator.next (<anonymous>)
      at node_modules/tslib/tslib.js:169:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/tslib/tslib.js:165:16)
      at handleRequest (node_modules/@contentstack/delivery-sdk/src/lib/cache.ts:12:14)
      at Object.<anonymous> (node_modules/@contentstack/delivery-sdk/src/lib/contentstack.ts:97:30)
      at Generator.next (<anonymous>)
```

The errors occur regardless of the `storeType` that is configured for the cache options. A sample of the stack config is

```js
{
  host: 'cdn.**-contentstack.com',
  apiKey: '***',
  deliveryToken: '***',
  environment: 'qa',
  cacheOptions: { policy: 'CACHE_ELSE_NETWORK', storeType: 'localStorage' },
  timeout: 5000,
  retryLimit: 3,
  retryDelay: 500
}
```

**Comment by cs-raj** [comment]
Hi @ADNolan we have taken this issue and we will update once we verify and resolve from our end

**Comment by maksymtulushads** [comment]
Hey, are there any updates on this?
I'm getting the same issue on v4.4.4
It looks like `defaultAdapter` is an array `['xhr', 'http', 'fetch']` and inside `stack()` when you create an adapter with caching you're passing it down to `handleRequest` function, so basically here you're trying to call an array: https://github.com/contentstack/contentstack-typescript/blob/f2728bbd97f1c59e29729c97bd80e699210604f7/src/lib/cache.ts#L17

**Comment by vkalta** [comment]
Hi @ADNolan and @maksymtulushads this issue has been resolved. Please check and confirm here so we can close this issue.

**Comment by nadeem-cs** [comment]
Closing this issue since it is resolved from our end. Please reopen it if you face any issue further.
